[package]
name = "process_pending_transfers"
type = "bin"
authors = [""]
compiler_version = ">=0.17.0"

[dependencies]
bjj = { tag = "v0.2.0", git = "https://github.com/jat9292/noir-elgamal" }
utils = { path="../utils" }