encrypted_values = [ ]

[balance_old_to_encrypted_1]
x = "0x0"
y = "0x0"

[balance_old_to_encrypted_2]
x = "0x0"
y = "0x0"

[balance_new_to_encrypted_1]
x = "0x0"
y = "0x0"

[balance_new_to_encrypted_2]
x = "0x0"
y = "0x0"
