[workspace]
members = [
    "circuits/transfer",
    "circuits/lock",
    "circuits/withdraw",
    "circuits/process_pending_deposits",
    "circuits/process_pending_transfers",
    "circuits/add_eth_signers",
    "circuits/extensions/fundraiser/correct_zero",
    "circuits/extensions/fundraiser/met_threshold",
    "circuits/extensions/fundraiser/correct_addition",
]
default-member = "circuits/transfer"

