[package]
name = "utils"
type = "lib"
authors = [""]
compiler_version = ">=0.18.0"

[dependencies]
bjj = { tag = "v0.2.0", git = "https://github.com/Bank-of-JubJub/noir-elgamal" }
ecrecover = { tag = "v0.1.0", git = "https://github.com/Bank-of-JubJub/ecrecover-noir" }
