[package]
name = "utils"
type = "lib"
authors = [""]
compiler_version = ">=0.18.0"

[dependencies]
bjj = { tag = "v0.2.0", git = "https://github.com/jat9292/noir-elgamal" }
ecrecover = { tag = "v0.19.0", git = "https://github.com/colinnielsen/ecrecover-noir" }
