[package]
name = "transfer_eth_signer"
type = "bin"
authors = [""]
compiler_version = ">=0.19.2"

[dependencies]
bjj = { tag = "v0.2.0", git = "https://github.com/jat9292/noir-elgamal" }
ecrecover = { tag = "v0.19.0", git = "https://github.com/colinnielsen/ecrecover-noir" }
utils = { path="../utils" }